### PR TITLE
Support for phpunitkit

### PR DESCRIPTION
**Pull request by wingsline**

### CODE REVIEW

**Comment by michaeldyrynda** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by michaeldyrynda** [comment]
Hey @wingsline - do you have a screenshot of this working? I've been playing around with it, but can't seem to make any changes to the output work.

**Comment by wingsline** [comment]
Yup, here is the screenshot.

In order to work, you need to set the `phpunit.color_scheme` in the sublime preferences also to this theme.

```json
{
"phpunit.color_scheme": "Packages/Laravel Colour Scheme/Laravel.tmTheme",
}
```

Here is the screenshot: 
screen shot 2017-09-19 at 9 32 26 pm

**Comment by michaeldyrynda** [comment]
Ah, needing the extra configuration parameter is a bit grim. I have tweaked what you've added though. Will see if I can make it play nicely. Standby!

**Comment by michaeldyrynda** [comment]
It also seems that they're removing custom colour scheme support - https://github.com/gerardroche/sublime-phpunit/blob/master/plugin.py#L408-L423

**Comment by wingsline** [comment]
hmm yeah, we should wait then until v3 lands then add the required syntax.

**Comment by michaeldyrynda** [comment]
Closing for now until phpunitkit decides how they're moving forward with theming. May need to submit a PR to their repo for it.

**Pull request closed without merging**
